try:
    from .version import version as __version__
except ImportError:
    # version.py is generated by setuptools_scm at build time, so it is absent
    # when running from a bare checkout. Fall back to the installed
    # distribution's metadata, and to a placeholder if that is missing too.
    from importlib.metadata import version, PackageNotFoundError

    try:
        __version__ = version("curitz")
    except PackageNotFoundError:
        __version__ = "master"
